# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/x509-certificate-exporter
  goos:
  - linux
  - freebsd
  - openbsd
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w
archives:
- name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  format: zip
nfpms:
- file_name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  homepage:  https://github.com/sylr/x509-certificate-exporter
  formats:
  - deb
  - rpm
checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
